### ISSUE TITLE
Stockage données

### ISSUE THREAD

**Issue by luciegaba** [luciegaba/MeteoFrance-Rain-Forecasting#1]
Trouver une méthode pour stocker les données tel que Bucket S3
Données d'origines dans "grounds_stations":
https://meteonet.umr-cnrm.fr/dataset/data/NW/
https://meteonet.umr-cnrm.fr/dataset/data/SE/
Il faudra s'assurer que tout soit dézippé et dans un même repo

**Comment by luciegaba** [comment]
Il faut que ce soit accessible depuis le notebook "project"

**Comment by ghiles10** [comment]
fait
